const data = [
  { id:'1',
  name: 'Known-Unknown',
  size:'24 x 24 inches',
  year:"2021",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (20).png',
},
{ id:'2',
  name: 'The Angels Meet',
  size:'24 x 24 inches',
  year:"2021",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (21).png',
},
{ id:'3',
  name: 'Despair',
  size:'24 x 24 inches',
  year:"2021",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (22).png',
},
{ id:'4',
  name: 'UNTITLED',
  size:'72 x 24 inches',
  year:"2023",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (33).png',
},
{ id:'5',
  name: 'Once a Lunar Eclips',
  size:'24 x 24 inches',
  year:"2021",
  medium:'Acrylic on Canvas',
  url:'/artworks/1 (19).png',
},
{ id:'6',
  name: '1000 miles',
  size:'72 x 46 inches',
  year:"2020",
  medium:'Dry Pastel on Paper',
  url:'/artworks/1 (18).png',
},
]

export default data;